import React from 'react';

export default function RRI() {
  return (
    <section data-testid="rri-section" className="section active">
      <div className="static-content">
        <div className="static-card">
          <h3>Responsible Research and Innovation (RRI)</h3>
          <p>The programme is committed to conducting research responsibly, ensuring that its scientific advances benefit society while minimising potential harms. Our RRI framework covers four pillars:</p>
        </div>

        <div className="rri-pillars">
          <div className="rri-pillar">
            <div className="rri-pillar-icon" style={{ backgroundColor: '#EFF6FF', color: '#2E5A88' }}>1</div>
            <h4>Anticipation</h4>
            <p>We systematically assess the potential impacts of our research on food systems, public health, and society. Each project includes an impact assessment that considers both intended and unintended consequences of computational gastronomy technologies.</p>
          </div>

          <div className="rri-pillar">
            <div className="rri-pillar-icon" style={{ backgroundColor: '#F0FDF4', color: '#1B6B4A' }}>2</div>
            <h4>Inclusion</h4>
            <p>Our research actively involves diverse stakeholders including chefs, food producers, consumers, policymakers, and communities with traditional food knowledge. We ensure that computational gastronomy serves diverse culinary traditions and dietary needs, not just commercial interests.</p>
          </div>

          <div className="rri-pillar">
            <div className="rri-pillar-icon" style={{ backgroundColor: '#FFF7ED', color: '#F59E0B' }}>3</div>
            <h4>Reflexivity</h4>
            <p>Our researchers regularly reflect on their assumptions, methods, and the broader implications of their work. We hold quarterly RRI review sessions where teams discuss ethical dimensions of their projects and receive feedback from our advisory board.</p>
          </div>

          <div className="rri-pillar">
            <div className="rri-pillar-icon" style={{ backgroundColor: '#FDF2F8', color: '#8B2252' }}>4</div>
            <h4>Responsiveness</h4>
            <p>We adapt our research directions based on emerging societal needs and ethical considerations. Our governance structure enables rapid response to new challenges, including mechanisms for pausing or redirecting research if significant concerns arise.</p>
          </div>
        </div>

        <div className="static-card">
          <h4>Key RRI Policies</h4>
          <ul className="rri-policies">
            <li>All projects must complete an RRI impact assessment before commencing experimental work</li>
            <li>Data from human sensory panels is collected with informed consent and stored according to GDPR</li>
            <li>Gene-edited crop varieties undergo additional biosafety review before any field trials</li>
            <li>IP generated by the programme is managed to ensure broad access to fundamental research tools</li>
            <li>Public engagement activities are conducted at least twice annually to share findings and gather feedback</li>
            <li>Environmental impact assessments are required for projects involving new food production methods</li>
          </ul>
        </div>

        <div className="static-card">
          <h4>Contact</h4>
          <p>For questions about our RRI framework, contact the Responsible Exploitation and Translation Officer (RETO): <strong>Amara Osei</strong> (a.osei.reto@thornbridge.ac.uk)</p>
        </div>
      </div>
    </section>
  );
}
